baseURL = "https://futuresfestival.online/"
languageCode = "en-us"
title = "Futures Festival Conference - Association of Professional Futurists"
theme = "serif"

[contact]
  email = "info@futuresfestival.online"

[params]
  google_analytics = "UA-165918763-1"

  [params.contact]
    email = "info@futuresfestival.online"

  [params.logo]
    mobile = "images/logo.jpg"
    standard  = "images/logo.jpg"
    alt = "Futures Festival Online '20"

[menu]
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
      weight = 1